#if !canImport(ObjectiveC)
import XCTest

extension EnvironmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnvironmentTests = [
        ("testArray", testArray),
        ("testCGFloatConformance", testCGFloatConformance),
        ("testCustomEnumConformance", testCustomEnumConformance),
        ("testDataConformance", testDataConformance),
        ("testDefaultEnumConformance", testDefaultEnumConformance),
        ("testDictionary", testDictionary),
        ("testDynamicMemberSubscripts", testDynamicMemberSubscripts),
        ("testEmptyStringArray", testEmptyStringArray),
        ("testEmptyStringDictionary", testEmptyStringDictionary),
        ("testEmptyStringSet", testEmptyStringSet),
        ("testSet", testSet),
        ("testStandardLibraryTypes", testStandardLibraryTypes),
        ("testStaticDynamicMemberSubscripts", testStaticDynamicMemberSubscripts),
        ("testStaticSubscripts", testStaticSubscripts),
        ("testSubscripts", testSubscripts),
        ("testURLConformance", testURLConformance),
        ("testUUIDConformance", testUUIDConformance),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EnvironmentTests.__allTests__EnvironmentTests),
    ]
}
#endif
